// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyG8ErYe1s0iVrJwlsIYFEvj6AvVcu9JM',
    appId: '1:775179144681:web:760fb75afd3ab85df0cf78',
    messagingSenderId: '775179144681',
    projectId: 'flutter-ddd-example-app',
    authDomain: 'flutter-ddd-example-app.firebaseapp.com',
    storageBucket: 'flutter-ddd-example-app.appspot.com',
    measurementId: 'G-GF4B7FX9C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIoZcB_BAkbS83pQQ0OfDSVnY26hyJDOM',
    appId: '1:775179144681:android:975ce4d2891f9a54f0cf78',
    messagingSenderId: '775179144681',
    projectId: 'flutter-ddd-example-app',
    storageBucket: 'flutter-ddd-example-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsJoQGrfckePlbqIHCN9hJba_qhKVrsc',
    appId: '1:775179144681:ios:70b688c8c882d261f0cf78',
    messagingSenderId: '775179144681',
    projectId: 'flutter-ddd-example-app',
    storageBucket: 'flutter-ddd-example-app.appspot.com',
    iosClientId: '775179144681-sd01mhedss55h5b2290vcf0cjim14f5v.apps.googleusercontent.com',
    iosBundleId: 'com.yaiceltg.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPsJoQGrfckePlbqIHCN9hJba_qhKVrsc',
    appId: '1:775179144681:ios:e473dca43fa17581f0cf78',
    messagingSenderId: '775179144681',
    projectId: 'flutter-ddd-example-app',
    storageBucket: 'flutter-ddd-example-app.appspot.com',
    iosClientId: '775179144681-m0mhhimgq0foo1tlacjvie4fk1idkk90.apps.googleusercontent.com',
    iosBundleId: 'com.yaiceltg.app.RunnerTests',
  );
}
